name: Build and deploy docs to GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - "docs/**"

jobs:
    build-and-upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Upload artifact for GitHub Pages
              uses: actions/upload-pages-artifact@v1
              with:
                  path: "docs"

    deploy-pages:
        needs: build-and-upload
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1
